
spring:
  application:
    name: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/artsail_admin
    username: moderlick
    password: 777
  session:
    timeout: 86400
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

ai:
  detection:
    url: http://127.0.0.1:9001/detect
  upload-dir: uploads/ai
